# Generated by Django 3.2.16 on 2023-01-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
