# Generated by Django 3.2.16 on 2023-01-11 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'ordering': ['created_on']},
        ),
    ]
